task :run => :build do
  sh "docker run -it --rm --platform=linux/amd64 -p 9000:8080 --env-file local.env radicaster/rec-radiko:latest"
end

task :build do
  sh "docker build --platform linux/amd64 -t radicaster/rec-radiko ."
end

task :push => :build do
  sh "aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 164278227419.dkr.ecr.ap-northeast-1.amazonaws.com"
  sh "docker tag radicaster/rec-radiko:latest 164278227419.dkr.ecr.ap-northeast-1.amazonaws.com/radicaster/rec-radiko:latest"
  sh "docker push 164278227419.dkr.ecr.ap-northeast-1.amazonaws.com/radicaster/rec-radiko:latest"
end
