import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";
import { GlobalHeader } from "./components/GlobalHeader";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mPlusRounded = M_PLUS_Rounded_1c({
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
  variable: "--font-m-plus-rounded",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${mPlusRounded.variable} font-sans antialiased bg-[#f8f9fa] text-[#2c3e50]`}>
        <div className="min-h-screen flex flex-col">
          <GlobalHeader />
          <main className="flex-1 w-full p-4 md:p-8">
            <div className="max-w-7xl mx-auto w-full">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
