source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "~> 2.7.0"

gem "rake", "~> 12.0"
gem "aws-sdk-s3"
gem "rspec", "~> 3.0"
gem "rspec-its"
gem "rspec-parameterized"
gem "rspec-mocks"
